"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { Archive, Copy, ExternalLink, MoreHorizontal, Pencil, Send, Trash2, Unlink } from "lucide-react";
import type { CatalogDto } from "@/types/catalog";

export function CatalogCard({ catalog, onChanged }: { catalog: CatalogDto; onChanged: () => void }) {
  const [menu, setMenu] = useState(false); const [busy, setBusy] = useState(false); const root = useRef<HTMLDivElement>(null);
  useEffect(() => { const close = (event: MouseEvent) => { if (!root.current?.contains(event.target as Node)) setMenu(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, []);
  async function action(path: string, method = "POST", body?: object) {
    setBusy(true); try { const response = await fetch(`/api/catalogs/${catalog.id}${path}`, { method, headers: body ? { "Content-Type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Action failed."); await onChanged(); } catch (error) { window.alert(error instanceof Error ? error.message : "Action failed."); } finally { setBusy(false); setMenu(false); }
  }
  async function copyLink() { await navigator.clipboard.writeText(catalog.publicUrl); setMenu(false); }
  const canPreview = Boolean(catalog.sourcePdfUrl) && catalog.status !== "failed";
  return <article className="catalog-card"><div className="catalog-cover"><div className="catalog-cover-placeholder">RK</div><span className={`status-pill ${catalog.status}`}>{catalog.status}</span></div><div className="catalog-body"><div className="catalog-collection">{catalog.collection}{catalog.season ? ` · ${catalog.season}` : ""}</div><h2 className="catalog-title" title={catalog.title}>{catalog.title}</h2><div className="catalog-meta"><span>{catalog.pageCount || "—"} pages</span><span>{catalog.views.toLocaleString()} views</span><span>{new Date(catalog.updatedAt).toLocaleDateString(undefined, { day: "2-digit", month: "short" })}</span></div><div className="catalog-actions">{canPreview ? <Link className="btn btn-secondary" href={`/admin/catalogs/${catalog.id}/preview`}>Preview</Link> : <button className="btn btn-secondary" disabled>PDF URL needed</button>}{catalog.status === "imported" && <button className="btn btn-primary" disabled={busy} onClick={() => action("/publish")}><Send size={12} /> Publish</button>}{catalog.status === "published" && <a className="btn btn-primary" href={catalog.publicUrl} target="_blank" rel="noreferrer"><ExternalLink size={12} /> Open</a>}<div className="more" ref={root}><button className="icon-btn" type="button" aria-label="More actions" aria-expanded={menu} onClick={() => setMenu(!menu)}><MoreHorizontal size={18} /></button>{menu && <div className="action-menu"><Link href={`/admin/catalogs/${catalog.id}/edit`}><Pencil size={14} /> Edit details</Link>{catalog.status === "published" && <button type="button" onClick={() => action("/unpublish")}><Unlink size={14} /> Unpublish</button>}{catalog.status === "published" && <button type="button" onClick={copyLink}><Copy size={14} /> Copy public link</button>}<button type="button" onClick={() => action("/duplicate")}><Copy size={14} /> Duplicate</button>{catalog.status !== "archived" && <button type="button" onClick={() => action("", "PUT", { status: "archived" })}><Archive size={14} /> Archive</button>}<button className="danger" type="button" onClick={() => { if (window.confirm(`Delete “${catalog.title}”? This cannot be undone.`)) void action("", "DELETE"); }}><Trash2 size={14} /> Delete</button></div>}</div></div></div></article>;
}
